### ISSUE TITLE
Issue3. Quadra nutrients QC not running from Terminal (see comment below for error) - Plot function will not run properly via. looping...

### ISSUE THREAD

**Issue by kdubss** [kdubss/HOP-Website-Dev#4]
```
bash-3.2$ python master_qc.py --data nuts --region Quadra --path Excel\ Files/2017-06-05_140201_HakaiData_nutrients_Quadra.xlsx

Now generating Nutrients Time Series figures for QC, for station in the Quadra region.
Traceback (most recent call last):
  File "master_qc.py", line 770, in <module>
    plot_nutrients(each_sta, each_sta, args.region)
  File "master_qc.py", line 334, in plot_nutrients
    for each_depth in nut_dict[sta_name][each_nut].keys():
TypeError: string indices must be integers
```

The TypeError may signify some depths are actually input as strings instead of integers.

**Comment by kdubss** [comment]
Testing the `plot_nutrients()` function with each Quadra station sampled works smoothly.

**Comment by kdubss** [comment]
```
def plot_nutrients(nut_dict, sta_name):
    '''
    Function to plot the nutrient time series for each station for all depths sampled.

    Inputs:
        1.  "nut_dict"  :  Dictionary object returned from the function 
                           'get_nutrients_at_all_depths(df)'.

        2.  "sta_name"  :  Str object specifying the station name.

        3.  "region"  :  Str object specifying the region name of study (e.g. Calvert)
    '''
    nutrients = ['PO4', 'SiO2', 'NO2+NO3 (uM)']

    for each_nut in nutrients:

        mpl.rc('font', family = 'serif')
        fig, axs = plt.subplots(1, 1)
        fig.set_figwidth(17)
        fig.set_figheight(12)
        spines2cut = ['top', 'right']

        for ax in fig.get_axes():

            if each_nut == 'PO4':
                ax.set_ylabel('PO$_4$ ($\mu$g.l$^{-1}$)\n', fontsize = 19)
            elif each_nut == 'SiO2':
                ax.set_ylabel('SiO$_2$ ($\mu$g.l$^{-1}$)\n', fontsize = 19)
            elif each_nut == 'NO2+NO3 (uM)':
                ax.set_ylabel('NO$_2$ & NO$_3$ ($\mu$g.l$^{-1}$)\n', fontsize = 19)
            for spine in spines2cut:
                ax.spines[spine].set_visible(False)
            for ylabel in ax.get_yticklabels():
                ylabel.set_fontsize(15)
            for xlabel in ax.get_xticklabels():
                xlabel.set_fontsize(15)

            ax.yaxis.set_ticks_position('none')
            ax.xaxis.set_ticks_position('none')

            if (sta_name == 'PRUTH') & (each_nut == 'PO4'):
                ax.set_title('%s time series\n(station %s)\n' % ('$PO$$_4$', 'Pruth'), fontsize = 21)
            elif (sta_name == 'PRUTH') & (each_nut == 'SiO2'):
                ax.set_title('%s time series\n(station %s)\n' % ('$SiO$$_2$', 'Pruth'), fontsize = 21)
            elif (sta_name == 'PRUTH') & (each_nut == 'NO2+NO3 (uM)'):
                ax.set_title('%s time series\n(station %s)\n' % ('$NO$$_2$ & $NO$$_3$', 'Pruth'), fontsize = 21)
            if each_nut == 'PO4':
                ax.set_title('%s time series\n(station %s)\n' % ('$PO$$_4$', sta_name), fontsize = 21)
            elif each_nut == 'SiO2':
                ax.set_title('%s time series\n(station %s)\n' % ('$SiO$$_2$', sta_name), fontsize = 21)
            elif each_nut == 'NO2+NO3 (uM)':
                ax.set_title('%s time series\n(station %s)\n' % ('$NO$$_2$ & $NO$$_3$', sta_name), fontsize = 21)

            for each_depth in nut_dict[sta_name][each_nut].keys():

                if (each_depth >= 0) & (each_depth <= 5):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 0.25, label = str(each_depth), 
                        color = 'blue')
                elif (each_depth > 5) & (each_depth <= 10):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 0.65, label = str(each_depth),
                        color = 'darkblue')
                elif (each_depth > 10) & (each_depth <= 30):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 0.45, label = str(each_depth),
                        color = '0.4')
                elif (each_depth > 30) & (each_depth <= 100):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 0.45, label = str(each_depth), 
                        color = 'green')
                elif (each_depth > 100) & (each_depth <= 200):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, label = str(each_depth),
                        color = 'darkgreen')
                elif (each_depth > 200) & (each_depth <= 275):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, label = str(each_depth),
                        color = '0.7')
                ##  > Pruth
                if (each_depth == 999):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '50 - bottom (75)', 
                            color = 'purple')
                # if (each_depth == 998):
                #     ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                #             label = '> 65 - bottom (75)', 
                #             color = 'purple')
                ##  > DFO2
                if (each_depth == 997):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '250 - bottom (333)', 
                            color = 'purple')
                # if (each_depth == 996):
                #     ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                #             label = '> 310 - bottom (333)', 
                #             color = 'purple')
                ##  > QCS01
                if (each_depth == 995):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 0.8, 
                            label = '> 100 - bottom (125)', 
                            color = 'purple')
                # if (each_depth == 994):
                #     ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                #             label = '> 110 - bottom (143)', 
                #             color = 'purple')
                ##  > FZH01
                if (each_depth == 993):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 200 - bottom (290)', 
                            color = 'purple')
                ##  > KC10
                if (each_depth == 992):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 200 - bottom (345)', 
                            color = 'purple')
                ##  > UBC7
                if (each_depth == 991):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 110 - bottom (163)', 
                            color = 'purple')
                ##  > FHE04
                if (each_depth == 990):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '20 - bottom (33)', 
                            color = 'purple')
                ##  > FZH08:
                if (each_depth == 989):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '200 - bottom (420)', 
                            color = 'purple')
                ##  > FZH10:
                if (each_depth == 988):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '300 - bottom (336)', 
                            color = 'purple')
                ## > HKP01:
                if (each_depth == 987):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '>100 - bottom (300)', 
                            color = 'purple')
                # if (each_depth == 986):
                #     ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                #             label = '> 275 - bottom (300)', 
                #             color = 'purple')
                ##  > KC11:
                if (each_depth == 985):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '70 - bottom (78)', 
                            color = 'purple')
                ##  > KC12:
                if (each_depth == 984):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 5 - bottom (22)', 
                            color = 'purple')
                ##  > KC15:
                if (each_depth == 983):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 20 - bottom (28)', 
                            color = 'purple')
                ##  > KC16:
                if (each_depth == 982):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 20 - bottom (35)', 
                            color = 'purple')
                ##  > KFPS04:
                if (each_depth == 981):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 10 - bottom (13)', 
                            color = 'purple')
                ##  > KIL03:
                if (each_depth == 980):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 30 - bottom (65)', 
                            color = 'purple')
                ##  > KME03:
                if (each_depth == 979):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 10 - bottom (17)', 
                            color = 'purple')
                ##  > KWY01:
                if (each_depth == 978):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 5 - bottom (12)', 
                            color = 'purple')
                ##  > NBCH01:
                if (each_depth == 977):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 5 - bottom (15)', 
                            color = 'purple')
                ##  > NMU03:
                if (each_depth == 976):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 10 - bottom (18)', 
                            color = 'purple')
                ##  > QSD02:
                if (each_depth == 975):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 100 - bottom (180)', 
                            color = 'purple')
                ##  > RVRS01:
                if (each_depth == 974):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 100 - bottom (115)', 
                            color = 'purple')
                ##  > WBCH01:
                if (each_depth == 973):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '> 5 - bottom (8)', 
                            color = 'purple')
                ##  > QU17:
                if (each_depth == 972):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = "%s 160 - bottom (170)" % '$\geq$', color = 'purple')
                #  > QU24:
                if (each_depth == 971):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = "%s 240 - bottom (265)" % "$\geq$", color = 'purple')
                ##  > QU29:
                if (each_depth == 970):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = "%s 120 - bottom (140)" % '$\geq$', color = 'purple')
                if (each_depth == 969):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = "%s 100 - bottom (108)" % '$\geq$', color = 'purple')
                if (each_depth == 968):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = "%s 200 - bottom (340)" % '>', color = 'purple')
                if (each_depth == 967):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = "%s 300 - bottom (500)" % '>', color = 'purple')
                if (each_depth == 966):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = "%s 200 - bottom (265)" % '>', color = 'purple')
                # if (each_depth == 966.5): ---> For combined stations QU24 + QU39.
                #     ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                #             label = "" , color = 'purple')
                if (each_depth == 965):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = "%s 300 - bottom (500)" % '>', color = 'purple')
                if (each_depth == 964):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = "%s 100 - bottom (115)" % '$\geq$', color = 'purple')
                ##  > DFO5:
                if (each_depth == 963):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '%s 150 - bottom (198)' % '>', color = 'purple')
                ##  > FHE02:
                if (each_depth == 962):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '%s 150 - bottom (180)' % '>', color = 'purple')
                ##  > KC7:
                if (each_depth == 961):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '%s 150 - bottom (168)' % '>', color = 'purple')
                ##  > MEA02:
                if (each_depth == 960):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '%s 30- bottom (54)' % '>', color = 'purple')
                ##  > NLU03:
                if (each_depth == 959):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '%s 30 - bottom (55)' % '>', color = 'purple')
                ##  > QSD05 a.:
                if (each_depth == 958):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                            label = '%s 30 - 100' % '>', color = 'orange')
                ##  > UBC8:
                if (each_depth == 956):
                    ax.plot(nut_dict[sta_name][each_nut][each_depth], 'o-', ms = 10, lw = 2.2, alpha = 1, 
                                label = '%s 10 - bottom (20)' % '>', color = 'purple')
            if sta_name == 'KC10':
                ax.legend(loc = 'best', prop = {'size' : 14}, fancybox = True, ncol = 2, bbox_to_anchor = (0.28, 1.15))
            else:
                ax.legend(loc = 'best', prop = {'size' : 14}, fancybox = True, ncol = 2, bbox_to_anchor = (0.35, 1.15))
            ax.get_legend().get_frame().set_facecolor('wheat')
            ax.get_legend().set_title('Depths Sampled (m)')
            ax.get_legend().get_title().set_fontsize(14)
            ax.get_legend().get_title().set_color('darkred')
            ax.get_legend().get_frame().set_alpha(1)
            ax.set_xlim((dt.date(2012, 5, 1), dt.date.today()))

    plt.show()
```
Testing with the above function in QT console works fine...

**Comment by kdubss** [comment]
Above code with remiaining parts, 

```
make_folder_4_figs(region)

            fig_name = '%s_sta_%s.png' % (each_nut, sta_name)
            fig.savefig('QC_Figs/' + region + '/' + fig_name)

            plt.clf()
            plt.close()
```

...works smoothly when run in the QT console.

**Comment by kdubss** [comment]
Problem was empty entries for ```Line Out Depth```.

**Comment by kdubss** [comment]
Issue fully resolved now for Quadra nutrients.

The problem seemed to lie with the ```drop_empty_rows()``` function, as the way the function was written, the argument (a str object) was parsed into it's alphabetical constituents, which are not part of any of the column headers in the data file.
