### ISSUE TITLE
Testing Chlorophyll for Calvert - Traceback error from Terminal

### ISSUE THREAD

**Issue by kdubss** [kdubss/HOP-Website-Dev#5]
```
Traceback (most recent call last):
  File "master_qc.py", line 1025, in <module>
    plot_size_fractioned_chl_all_depths(chlorophyll_data, schl, each_sta, args.data, args.region)
  File "master_qc.py", line 624, in plot_size_fractioned_chl_all_depths
    plot_size_fractioned_chl(parsed_chl_dict, sta_name, each_depth, data_type, region)
  File "master_qc.py", line 752, in plot_size_fractioned_chl
    ax.plot(parsed_chl_dict[sta_name][depth][20], 'bo', ms = 16, alpha = 0.4, label = '20 $\mu$m')
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/__init__.py", line 1892, in inner
    return func(ax, *args, **kwargs)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 1407, in plot
    self.add_line(line)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 1787, in add_line
    self._update_line_limits(line)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 1809, in _update_line_limits
    path = line.get_path()
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/lines.py", line 989, in get_path
    self.recache()
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/lines.py", line 676, in recache
    x = np.asarray(xconv, np.float_)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: '2017-05-18'
```

**Comment by kdubss** [comment]
Explicitly defining the parsed indices as a <b><code>pd.to_datetime</code></b> seemed to resolve the above Traceback error but also resulted in the <b><code>FileNotFoundError</code></b> (below)
```
Now generating Chlorophyll Time Series figures for QC, for stations in the Calvert region.
Traceback (most recent call last):
  File "master_qc.py", line 1024, in <module>
    plot_size_fractioned_chl_all_depths(chlorophyll_data, schl, each_sta, args.data, args.region)
  File "master_qc.py", line 624, in plot_size_fractioned_chl_all_depths
    plot_size_fractioned_chl(parsed_chl_dict, sta_name, each_depth, data_type, region)
  File "master_qc.py", line 774, in plot_size_fractioned_chl
    fig.savefig('QC_figs/' + region + '/' + data_type + '/' + fig_name)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/figure.py", line 1572, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2244, in print_figure
    **kwargs)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 550, in print_png
    filename_or_obj = open(filename_or_obj, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'QC_figs/Calvert/Chlorophyll/Chla_PRUTH_0 m.png'
```
Seems like the folders are not being created as they should.

**Comment by kdubss** [comment]
Issue resolved.

Needed to put the <b><code>make_folder_4_figs()</code></b> function into the plotting function.
