### ISSUE TITLE
Traceback ValueError - Testing Chlorophyll from terminal

### ISSUE THREAD

**Issue by kdubss** [kdubss/HOP-Website-Dev#6]
```
Traceback (most recent call last):
  File "master_qc.py", line 1033, in <module>
    plot_size_fractioned_chl_all_depths(chlorophyll_data, schl, each_sta, args.data, args.region)
  File "master_qc.py", line 624, in plot_size_fractioned_chl_all_depths
    plot_size_fractioned_chl(parsed_chl_dict, sta_name, each_depth, data_type, region)
  File "master_qc.py", line 778, in plot_size_fractioned_chl
    fig.savefig('QC_figs/' + region + '/' + data_type + '/' + fig_name)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/figure.py", line 1572, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 2244, in print_figure
    **kwargs)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 545, in print_png
    FigureCanvasAgg.draw(self)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/figure.py", line 1143, in draw
    renderer, self, dsu, self.suppressComposite)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 2409, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/axis.py", line 1136, in draw
    ticks_to_draw = self._update_ticks(renderer)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/axis.py", line 969, in _update_ticks
    tick_tups = [t for t in self.iter_ticks()]
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/axis.py", line 969, in <listcomp>
    tick_tups = [t for t in self.iter_ticks()]
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/axis.py", line 912, in iter_ticks
    majorLocs = self.major.locator()
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/dates.py", line 983, in __call__
    self.refresh()
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/dates.py", line 1003, in refresh
    dmin, dmax = self.viewlim_to_dt()
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/dates.py", line 760, in viewlim_to_dt
    return num2date(vmin, self.tz), num2date(vmax, self.tz)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/dates.py", line 401, in num2date
    return _from_ordinalf(x, tz)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/dates.py", line 254, in _from_ordinalf
    dt = datetime.datetime.fromordinal(ix).replace(tzinfo=UTC)
ValueError: ordinal must be >= 1
```

Code stopped after Station DFO5 at 10 m depth.

**Comment by kdubss** [comment]
20 m depth for DFO5 will not plot due to there being any values for any of the filter types.

Will have to find a way of integrating this into the python code.

**Comment by kdubss** [comment]
Adding ```.dropna()``` method in the ```get_size_fractioned_chl_at_all_depths()``` will resolve the matter.
