### ISSUE TITLE
No labelled objects for legend when there is no data 2 plot.

### ISSUE THREAD

**Issue by kdubss** [kdubss/HOP-Website-Dev#7]
```
UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "
Traceback (most recent call last):
  File "master_qc.py", line 1040, in <module>
    plot_size_fractioned_chl_all_depths(chlorophyll_data, schl, each_sta, args.data, args.region)
  File "master_qc.py", line 624, in plot_size_fractioned_chl_all_depths
    plot_size_fractioned_chl(parsed_chl_dict, sta_name, each_depth, data_type, region)
  File "master_qc.py", line 769, in plot_size_fractioned_chl
    ax.get_legend().set_title('Filter Type')
AttributeError: 'NoneType' object has no attribute 'set_title'
```

**Comment by kdubss** [comment]
Problem was if there was no data being plotted, there was no instances for legend labels, and hence, no legend instances.

Resolved by putting code for legend block under individual ```if``` statements for cases of each filter type having empty data.
