### ISSUE TITLE
ValueError (```could not convert string to float: '2016-11-11'```) in chlorophyll plot function

### ISSUE THREAD

**Issue by kdubss** [kdubss/HOP-Website-Dev#8]
```
Traceback (most recent call last):
  File "master_qc.py", line 1071, in <module>
    plot_size_fractioned_phaeo_all_depths(chlorophyll_data, sphaeo, each_sta, args.data, args.region)
  File "master_qc.py", line 646, in plot_size_fractioned_phaeo_all_depths
    plot_size_fractioned_phaeo(parsed_phaeo_dict, sta_name, each_depth, data_type, region)
  File "master_qc.py", line 691, in plot_size_fractioned_phaeo
    ax.plot(parsed_phaeo_dict[sta_name][depth][20], 'bo', ms = 16, alpha = 0.4, label = '20 $\mu$m')
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/__init__.py", line 1892, in inner
    return func(ax, *args, **kwargs)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 1407, in plot
    self.add_line(line)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 1787, in add_line
    self._update_line_limits(line)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 1809, in _update_line_limits
    path = line.get_path()
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/lines.py", line 989, in get_path
    self.recache()
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/matplotlib/lines.py", line 676, in recache
    x = np.asarray(xconv, np.float_)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: could not convert string to float: '2016-11-11'
```
May have to use ```pd.to_datetime()``` to explicitely define the indices as date times?

**Comment by kdubss** [comment]
Resolved by explicitly defining the indices as date times.
