### ISSUE TITLE
Parsing biomass per meter squared

### ISSUE THREAD

**Issue by kdubss** [kdubss/HOP-Website-Dev#9]
Error:
```
Traceback (most recent call last):
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/pandas/core/ops.py", line 652, in na_op
    raise_on_error=True, **eval_kwargs)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/pandas/computation/expressions.py", line 210, in evaluate
    **eval_kwargs)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/pandas/computation/expressions.py", line 121, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b, raise_on_error)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/pandas/computation/expressions.py", line 63, in _evaluate_standard
    return op(a, b)
TypeError: can't multiply sequence by non-int of type 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/pandas/core/ops.py", line 676, in safe_na_op
    return na_op(lvalues, rvalues)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/pandas/core/ops.py", line 658, in na_op
    result[mask] = op(x[mask], _values_from_object(y[mask]))
TypeError: can't multiply sequence by non-int of type 'float'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "master_qc.py", line 1231, in <module>
    biomass_per_m2 = get_size_fractioned_zooplankton_biomass_per_m2_4_all_stations(zoo_df)
  File "master_qc.py", line 1039, in get_size_fractioned_zooplankton_biomass_per_m2_4_all_stations
    'Line Out Depth'
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/pandas/core/ops.py", line 715, in wrapper
    result = wrap_results(safe_na_op(lvalues, rvalues))
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/pandas/core/ops.py", line 686, in safe_na_op
    lambda x: op(x, rvalues))
  File "pandas/src/algos_common_helper.pxi", line 1176, in pandas.algos.arrmap_object (pandas/algos.c:46681)
  File "/Users/kangwang/anaconda3/lib/python3.5/site-packages/pandas/core/ops.py", line 686, in <lambda>
    lambda x: op(x, rvalues))
TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')
```

**Comment by kdubss** [comment]
Problem:

There are instances of "SVC", "DE", "ND" in the <code>Volumetric Biomass Final</code> column, which is supposed to be full of numerical values.  The quality flags belong in the <code>Volumetric Biomass Final Quality Flag</code> column.

**Comment by kdubss** [comment]
Issue resolved by placing all instances of flags in the <code>Volumetric Biomass Final</code> column in the <code>Volumetric Biomass Final Quality Flag</code> column.
